import "./style.css";
import javascriptLogo from "./javascript.svg";
import viteLogo from "/vite.svg";
import { setupCounter } from "./counter.js";

document.querySelector("#app").innerHTML = `
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="${viteLogo}" class="logo" alt="Vite logo" />
    </a>
    <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank">
      <img src="${javascriptLogo}" class="logo vanilla" alt="JavaScript logo" />
    </a>
    <h1>Hello Vite!</h1>
    <div class="card">
      <button id="counter" type="button"></button>
    </div>
    <p class="read-the-docs">
      Click on the Vite logo to learn more
    </p>
  </div>
`;

// Generates pure HTML/CSS from visual builder
function generateInvoker(config) {
  return `
<!-- Generated by Invoke Playground -->
<button 
  popovertarget="${config.id}"
  ${config.animation ? `style="--popover-animation: ${config.animation}"` : ""}
>
  ${config.label}
</button>

<div 
  popover 
  id="${config.id}"
  ${config.position ? `anchor="${config.anchor}"` : ""}
>
  ${config.content}
</div>

<style>
  [popover] {
    animation: var(--popover-animation, none);
  }
</style>
  `;
}

setupCounter(document.querySelector("#counter"));
